[package]
name = "autotools-dependency"
version = "0.0.1"
authors = ["Daniel McClanahan <1305167+cosmicexplorer@users.noreply.github.com>"]

[dependencies]
reqwest = "0.8"
pathdiff = "0.1"
tar = "0.4"
tempdir = "0.3"
