[package]
name = "bfd-sys"
version = "0.1.0"
authors = ["Daniel McClanahan <1305167+cosmicexplorer@users.noreply.github.com>"]
links = "bfd"

[build-dependencies]
autotools-dependency = { path = "autotools-dependency" }
bindgen = "0.33.0"
tempdir = "0.3"
